import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { VitePWA } from "vite-plugin-pwa";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { renderIndexHtml } from "./server/spa/renderHead";

function jabolHeadInject(): Plugin {
  let warnedMissingPath = false;
  return {
    name: "jabol-head-inject",
    transformIndexHtml: {
      order: "pre",
      async handler(html, ctx) {
        const configPath = process.env.JABOL_CONFIG_PATH;
        if (!configPath) {
          if (!warnedMissingPath) {
            console.warn(
              "[jabol-head-inject] JABOL_CONFIG_PATH not set — serving static fallback head. Set it to enable dev head injection.",
            );
            warnedMissingPath = true;
          }
          return html;
        }
        try {
          const raw = await readFile(configPath, "utf8");
          const canonical = JSON.parse(raw) as {
            brand?: string;
            title?: string;
            description?: string;
            favicon?: string;
            image?: string;
          };
          const port = ctx.server?.config.server.port ?? 5173;
          const origin = `http://localhost:${port}`;
          return renderIndexHtml(html, {
            brand: canonical.brand,
            title: canonical.title,
            description: canonical.description,
            favicon: canonical.favicon,
            image: canonical.image,
            siteUrl: origin + (ctx.originalUrl ?? "/"),
            bootstrap: { ...canonical, readOnly: false },
          });
        } catch (err) {
          console.warn(
            `[jabol-head-inject] failed to read/parse ${configPath}: ${(err as Error).message}`,
          );
          return html;
        }
      },
    },
  };
}

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    jabolHeadInject(),
    VitePWA({
      // The service worker is registered manually from the SPA so we can show
      // an update prompt; see client/pwa/PWAUpdatePrompt.tsx.
      registerType: "prompt",
      injectRegister: null,
      // Icons live in `assets/` (publicDir) and are generated by
      // @vite-pwa/assets-generator — run `pnpm assets:generate`.
      includeAssets: ["favicon.svg", "favicon.ico", "apple-touch-icon-180x180.png"],
      manifest: {
        name: "jabol — Just A Bunch Of Links",
        short_name: "jabol",
        description: "A self-hosted link directory.",
        id: "/",
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#1e1e2e",
        theme_color: "#1e1e2e",
        icons: [
          { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
        screenshots: [
          {
            src: "screenshot.png",
            sizes: "3680x2392",
            type: "image/png",
            form_factor: "wide",
            label: "jabol link directory",
          },
        ],
      },
      workbox: {
        // Precache the app shell assets only. index.html is intentionally NOT
        // precached: the server re-renders its <head> per request (OG/meta
        // injection), so navigations use NetworkFirst (below) to stay fresh.
        globPatterns: ["**/*.{js,css,woff,woff2,svg}"],
        // Disable the plugin's default cache-first navigation fallback
        // (navigateFallback: "index.html") — the NetworkFirst runtimeCaching
        // route below handles navigations instead.
        navigateFallback: undefined,
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        runtimeCaching: [
          {
            // Navigations: always try the network so server-rendered head tags
            // are current; fall back to the last-cached document when offline.
            urlPattern: ({ request, sameOrigin }) =>
              sameOrigin && request.mode === "navigate",
            handler: "NetworkFirst",
            options: {
              cacheName: "jabol-pages",
              networkTimeoutSeconds: 3,
              expiration: { maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Cached favicons / OG images — immutable enough to serve cache-first.
            urlPattern: ({ url, sameOrigin }) =>
              sameOrigin && url.pathname.startsWith("/api/icons"),
            handler: "CacheFirst",
            options: {
              cacheName: "jabol-icons",
              expiration: { maxEntries: 500, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Link data — NetworkFirst so the directory still renders offline
            // from the last response. SSE (/api/events) and auth are excluded.
            urlPattern: ({ url, sameOrigin }) =>
              sameOrigin &&
              url.pathname.startsWith("/api/") &&
              !url.pathname.startsWith("/api/icons") &&
              url.pathname !== "/api/events" &&
              !url.pathname.startsWith("/api/auth"),
            handler: "NetworkFirst",
            options: {
              cacheName: "jabol-api",
              networkTimeoutSeconds: 5,
              expiration: { maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      // Avoid interfering with the dev proxy / HMR two-server setup.
      devOptions: { enabled: false },
    }),
  ],
  publicDir: "assets",
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "client"),
    },
  },
  server: {
    port: 5173,
    proxy: {
      "/api": "http://localhost:8080",
    },
  },
  build: {
    outDir: "dist",
    sourcemap: false,
  },
});
